[php]
file_uploads = On
upload_max_filesize = 64M
post_max_size = 64M
memory_limit = 64M
max_execution_time = 600

; Keep response headers available for sessions initialized during rendering.
output_buffering = 4096
implicit_flush = Off

[Date]
date.timezone = Europe/Prague
